services:
  # FastAPI Backend Web Service  
  - type: web
    name: git-time-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
    healthCheckPath: /health

  # React Frontend Static Site
  - type: web
    name: git-time-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_API_URL
        value: https://git-time-backend.onrender.com